### ISSUE TITLE
RI-04: trayectos

### ISSUE THREAD

**Issue by JSnow11** [IS-PGPI-G11/patinetsi#13]
# descripción
*como*: administrador

*quiero*: poder ver el tiempo y los km que han recorrido los usuarios y que patinetes han usado.

# to-do
- [x] investigar plugins
- [x] petición de cambio para la parte no realizable
- [x] descartar la parte no realizable ante la falta de resputesta

# aceptación
- [ ] el usuario puede ver el tiempo de uso de cada patinete

**Comment by JSnow11** [comment]
## to-do
- hacer petición del cambio para eliminar los km (distancia)

**Comment by ferrabled** [comment]
Petición de cambio enviada al equipo directivo ✔️

**Comment by JSnow11** [comment]
> Petición de cambio enviada al equipo directivo heavy_check_mark

@ferrabled ante la falta de respuesta se da por aceptada puesto que se debe cerrar el sprint

**Comment by JSnow11** [comment]
@ferrabled por favor, indica donde se puede ver el tiempo de uso con una url o pasos para llegar

**Comment by ferrabled** [comment]
> @ferrabled por favor, indica donde se puede ver el tiempo de uso con una url o pasos para llegar

Al igual que en la issue #8, para poder ver el tiempo comprado, debemos acceder a [mis pedidos](http://20.107.0.136/wordpress/index.php/mi-cuenta/orders/) y (tras realizar algún pedido) podremos ver los minutos usados en cada pedido. Esos minutos de uso, se corresponden a "elementos", por lo que en el pedido 103, se han usado 30 minutos. En el último pedido, se han usado 10 minutos 

![image](https://user-images.githubusercontent.com/48551658/145688422-d033ce84-09a6-4008-8f56-765a2bb95275.png)

**Comment by JSnow11** [comment]
## review
- en la sección de mis pedidos se pueden consultar los minutos de uso en cada caso
