### ISSUE TITLE
RF-05: Alquilar Patín

### ISSUE THREAD

**Issue by ferrabled** [IS-PGPI-G11/patinetsi#18]
# descripción
*como*: usuario

*quiero*: poder alquilar un patín.
 

# to-do
- [x] cambio a compra de minutos como cantidad del producto @JSnow11 
- [x] completar un pedido @ferrabled 

# aceptación
- [x] cada patín cuesta x cent por minuto 
- [x] la cantidad de compra de un patín es la cantidad de minutos comprados
- [x] se puede realizar un pedido y completarlo

**Comment by JSnow11** [comment]
# implementado
- los patines ya se alquilan por minuto (cantidad)

**Comment by JSnow11** [comment]
## implementado
- el cierre de pedido esta ahora disponible mediante el uso de transferencia bancaria

**Comment by pedalopon** [comment]
## Review
- Se ha realizado un pedido correctamente comprobando todos los criterios de aceptación
