### ISSUE TITLE
RF-11: pagos

### ISSUE THREAD

**Issue by JSnow11** [IS-PGPI-G11/patinetsi#19]
# descripción
*como*: usuario

*quiero*: o poder pagar la tarifa por paypal, bizum o tarjeta.

# to-do
- [x] Instalar plugin de WooCommerce que permita el pago con tarjeta y paypal
- [x] Configurar pago por transferencia bancaria

# aceptación
- [x] Poder comprar patines por transferencia bancaria
- [x] Los pedidos quedan registrados en la vista de administrador

# Nota
Si se quiere usar el pago con tarjeta o paypal se ha predispuesto todo para que nuestro cliente solo tenga que registrarse introduciendo su iban para activar este método de pago.

**Comment by JSnow11** [comment]
## to-do
- petición de cambio, eliminar bizum

**Comment by JSnow11** [comment]
## review
- funcionamiento correcto mediante transferencia bancaria
- el resto de opciones estan disponibles en el panel de administrador
