### ISSUE TITLE
RF-10: Estadísticas de administrador

### ISSUE THREAD

**Issue by pedalopon** [IS-PGPI-G11/patinetsi#20]
# descripción
*como*:  administrador

*quiero*:  poder consultar las siguientes estadísticas 

# to-do
- [x] Número de alquileres que llevo al día, mes y año
- [x] El tiempo y el dinero que llevan los patines acumulados al día, mes y año
- [x] El tiempo y el dinero que lleva acumulados un patín en concreto
- [x] El número de usuarios que tengo dado de alta en la aplicación

# aceptación
- [x] Se muestran en el panel de administración todas las estadísticas citadas

No olviden estimar temporalmente esta historia y planificarla dentro de la línea de producción del sprint en el que vaya a ser desarrollada.

**Comment by JSnow11** [comment]
# implementado

Esta y mucha mas información es consultable en el modulo de analitica de woo commerce:
http://20.107.0.136/wordpress/wp-admin/admin.php?page=wc-admin&path=%2Fanalytics%2Foverview

mas información es accesible mediante la barra de menu:
![image](https://user-images.githubusercontent.com/47798577/145027998-878626be-e985-4a88-8271-d9ae494258fc.png)


## funcionalidad solicitada en concreto
- El nº de alquileres es consultable en la overview, viendo **pedidos**
![image](https://user-images.githubusercontent.com/47798577/145028093-02e93d94-e1b5-4fe5-a2b1-4762a58ab8c0.png) o también en el apartado de [pedidos](http://20.107.0.136/wordpress/wp-admin/admin.php?page=wc-admin&path=%2Fanalytics%2Forders)

- El tiempo y dinero en general también es consultable como articulos (minutos) y ventas netas (coste de uso no de activación), observable en la imagen anterior o también en el apartado concreto de [ingresos](http://20.107.0.136/wordpress/wp-admin/admin.php?page=wc-admin&path=%2Fanalytics%2Frevenue)
- pueden realizarse consultas por patín en concreto, clicando en el patin dentro del modulo de analisis o mediante la url correspondiente, pe: http://20.107.0.136/wordpress/wp-admin/admin.php?page=wc-admin&filter=single_product&products=14&path=%2Fanalytics%2Fproducts

- los clientes pueden listarse en el apartado de [clientes](http://20.107.0.136/wordpress/wp-admin/users.php?role=customer): 
![image](https://user-images.githubusercontent.com/47798577/144494148-26f8820a-bc7d-4f0c-aa77-652c8d865be6.png)

**Comment by ferrabled** [comment]
Se ha comprobado la funcionalidad y se encuentra correctamente implementada ✔️
