### ISSUE TITLE
RN-05: Bono gratis por fidelidad

### ISSUE THREAD

**Issue by josaloroc** [IS-PGPI-G11/patinetsi#27]
# descripción
*como*: administrador
*quiero*: que los usuarios obtengan un desbloqueo gratuito por cada 10€ pagados
*para*: premiar la confianza con el cliente.

# to-do
- [x] Investigar sobre la creación de cupones
- [x] Crear cupón
- [x] si no es posible la creación automática cuando se acumulan 10€, se indica que el administrador debe gestionarlo manualmente y crearlos cuando corresponda

# aceptación
- [x] se aplica el descuento al aplicar el cupón.

**Comment by josaloroc** [comment]
Petición del cambio: no es posible establecer el bono comentado debido a las limitaciones en opciones que ofrecen diversos plugins sobre los que se han estado investigando. Se propondrá eliminar el requisito o establecer una bonificación o cupón más sencillo con las herramientas que se tienen por defecto con WooCommerce

**Comment by JSnow11** [comment]
> Petición del cambio: no es posible establecer el bono comentado debido a las limitaciones en opciones que ofrecen diversos plugins sobre los que se han estado investigando. Se propondrá eliminar el requisito o establecer una bonificación o cupón más sencillo con las herramientas que se tienen por defecto con WooCommerce

@josaloroc, este recurso puede resultar de interés: https://woocommerce.com/document/envio-gratuito/

**Comment by josaloroc** [comment]
Tras la resolución de la petición de cambio recibida, se acuerda que se aplicará un descuento sobre el producto en vez de otorgar un "desbloqueo" gratuito.

Debido a fallos con Woocommerce al implementar el descuento fijo sobre el producto, se ha establecido un descuento porcentual.
A partir de 2 horas, el precio del uso total del patín se verá reducido un 30%.

![image](https://user-images.githubusercontent.com/64849766/145684472-bfc19a6f-975c-44ad-8e58-f8267f16d9c9.png)

Para facilitar a los clientes el conocimiento de la existencia de este cupón, se ha añadido una nueva entrada informando del uso del cupón:
![image](https://user-images.githubusercontent.com/64849766/145684553-df89ab63-2210-4ba8-be9b-072991013b4e.png)

**Comment by JSnow11** [comment]
## review
- añadido el cupón de activación gratuita como ejemplo
- cupones funcionando correctamente
