### ISSUE TITLE
Config: entorno de desarrollo 

### ISSUE THREAD

**Issue by JSnow11** [IS-PGPI-G11/patinetsi#28]
# descripción
*como*: desarrollador

*quiero*: configurar el entorno de desarrollo

*para*: establecer una linea base de implementación

# to-do
- [x] crear el projecto wordpress
- [x] obtener una plataforma de hosting gratuita
- [x] facilitar cuentas de desarrollador
- [x] instalar plugins básicos
- [x] desplegar

# aceptación
- [x] panel de gestión accesible bajo `base_url/wp-admin`
- [x] pagina inicial accesible

No olviden estimar temporalmente esta historia y planificarla dentro de la línea de producción del sprint en el que vaya a ser desarrollada.

**Comment by JSnow11** [comment]
# Implementado
mediante el uso de azure

## review
- check  http://20.107.0.136/wordpress

**Comment by ferrabled** [comment]
Reviewed, all correct
