### ISSUE TITLE
RI-02: patinete

### ISSUE THREAD

**Issue by JSnow11** [IS-PGPI-G11/patinetsi#4]
# descripcion
**como**: usuario

**quiero**: poder consultar los siguientes datos de los patines eléctricos: 
- Número de identificador
- marca
- modelo
- localización actual
- estado
- código 
- QR/código asociado.

# to-do
- [x] añadir producto
- [x] consultar datos de los patines
- [x] #5 - Dar de alta patín  

# aceptacion
- [x] Dar de alta patines con todos los datos
- [x] Los patines se muestran con datos correctos

**Comment by ferrabled** [comment]
Los patinetes disponibles pueden encontrarse en el siguiente [link](http://20.107.0.136/wordpress/index.php/tienda/)
Tras pulsar en uno de los patinetes disponibles, para ver sus datos (Identificador, marca, modelo...), tenemos que pulsar sobre 
información adicional y veremos los siguientes datos:
![image](https://user-images.githubusercontent.com/48551658/143087641-d08399c7-b01b-4f30-b429-06ee0b3f7d65.png)

La descripción muestra un mapa con la localización del patinete.

**Comment by JSnow11** [comment]
# review
- funciona correctamente

## sugerencia
- cambiar el apartado de _Descripción_ para que ponga _Localización_ si fuera posible
