### ISSUE TITLE
RF-02: Dar de alta patín

### ISSUE THREAD

**Issue by ferrabled** [IS-PGPI-G11/patinetsi#5]
# descripción
**como**: administrador

**quiero**:  poder dar de alta un patinete en el sistema.

# to-do
- [x] Sistema para dar de alta patines en el sistema
- [x] Seleccionar datos de patinetes eléctricos según #4 
- [x] Explicación: Cómo dar de alta un patín

# aceptación
- [x] El sistema añade correctamente un patinete para su alquiler
- [x] Los patinetes cuentan con los datos necesarios mostrados en #4

**Comment by ferrabled** [comment]
Para la creación de un patinete nuevo, tenemos que ir a la siguiente dirección: [Añadir producto](http://20.107.0.136/wordpress/wp-admin/post-new.php?post_type=product), indicar un título al producto (Patinete-00X), y pulsar en Atributos para añadir para cada dato indicado en #4 . 
![image](https://user-images.githubusercontent.com/48551658/143088790-ee969da9-6e03-4200-bf13-f1292c3907ef.png)
También podemos añadirle una imagen al patinete desde la columna derecha "Imagen del producto".
Finalizamos pulsando en rellenar para publicar el nuevo patinete en el sistema.
