### ISSUE TITLE
RF-07: enviar incidencias

### ISSUE THREAD

**Issue by pedalopon** [IS-PGPI-G11/patinetsi#6]
# descripción
como:  usuario quiero
quiero: poder enviar una incidencia

# to-do
- [x] Instalar y configurar  un plugin de wordpress que permita crear formularios
- [x] Crear un formulario para el registro de incidencias

# aceptación
- [x] Se reciben incidencias de los usuarios correctamente desde el formulario de la pagina de contacto.

No olviden estimar temporalmente esta historia y planificarla dentro de la linea de producción del sprint en el que vaya a ser desarrollada.

**Comment by JSnow11** [comment]
## review
- funciona correctamente
