### ISSUE TITLE
RNF-01: Seguridad

### ISSUE THREAD

**Issue by josaloroc** [IS-PGPI-G11/patinetsi#7]
# descripcion
como: administrador
quiero: que la aplicación tenga un certificado SSL
para: transmitir seguridad a los usuarios

# to-do
- [x] investigar plugins
- [x] petición de cambio
- [x] descartar ante falta de respuesta

# aceptacion
- [ ] pagina segura y https disponible

**Comment by JSnow11** [comment]
## to-do
- petición de cambio. no hay dinero

**Comment by ferrabled** [comment]
Petición del cambio enviada al equipo directivo

**Comment by JSnow11** [comment]
## descarte
- la tarea es descartada, no hay respuesta a la petición de cambio pero el sprint debe darse por finalizado

**Comment by ferrabled** [comment]
Se ha finalizado instalando los plugins necesarios para poder colocar el certificadoS SSL y aumentar la seguridad de la página
![image](https://user-images.githubusercontent.com/48551658/145688309-468398aa-1b22-439b-9960-6ac6a04e3f48.png)

Faltaría comprar y añadir el certificado SSL para que funcione correctamente.
