### ISSUE TITLE
RF-08: tiempo y dinero consumido

### ISSUE THREAD

**Issue by pedalopon** [IS-PGPI-G11/patinetsi#8]
# descripción
*como*: usuario

*quiero*: saber el tiempo y el dinero que llevo consumido

# to-do
- [x] Se muestra el dinero gastado por el usuario en cada pedido que realiza (costo desbloqueo junto al costo por el tiempo)
- [x] Se muestra el tiempo gastado por el usuario en cada pedido que realiza

# aceptación
- [x] Se muestra el tiempo y el dinero consumido por el usuario

**Comment by JSnow11** [comment]
## repetido
- el tiempo ya existe en la tarea #13

**Comment by ferrabled** [comment]
Cuando un usuario se registra en la plataforma y realiza un pedido, se puede comprobar que el pedido se añade a nuestra cuenta. Podemos entrar en cualquier momento a [Mis pedidos](http://20.107.0.136/wordpress/index.php/mi-cuenta/orders/) donde nos muestra la siguiente información:

- Dinero Gastado
- Tiempo de uso

![image](https://user-images.githubusercontent.com/48551658/145034819-35215783-027e-4c23-b4f8-f03deeaa3d0d.png)

La información de Tiempo y Coste se indica en la columna **Total**.
Podemos ver que el tiempo se indica en "para **X** elementos", por lo que, el pedido # 103 indica una compra de 30 minutos, con un costo total de 5,5€ (4,5€ del tiempo de uso, y 1€ del desbloqueo)

**Comment by JSnow11** [comment]
## review
- la información esta disponible tal y como es indicado
