### ISSUE TITLE
RNF-02: posicionamiento SEO

### ISSUE THREAD

**Issue by josaloroc** [IS-PGPI-G11/patinetsi#9]
# descripción
*como*: administrador
*quiero*: que la aplicación deba estar optimizada
*para*: tener un buen posicionamiento SEO

# to-do
- [x] investigar plugins
- [x] petición de cambio
- [x] descarte ante la falta de respuesta

# aceptación
- [x] la pagina es fácilmente encontrable en google

**Comment by JSnow11** [comment]
## to-do
- petición del cambio, no hay dinero

**Comment by JSnow11** [comment]
## finalizada
- se da por finalizada, la estructura de wordpress + woocommerce por defecto muestra una optimización suficiente y no es mejorable mediante configuración básica, requeriría de programación. 

- Lighthouse indica más de un **80%** en **SEO**

Resultados de lighthouse:
![image](https://user-images.githubusercontent.com/47798577/145674691-19e193ae-6aa5-4aad-8b5d-6ac10082cc05.png)
